### ISSUE TITLE
Alternative ORMLite database types...

### ISSUE THREAD

**Issue by jsobell** [NetCoreTemplates/nextjs#3]
Is there any way to specify the required database type when using these mix templates?
I've been looking at using SQLServer instead of SQLite, and I can run the `x mix sqlserver` afterwards to override the type, but the template appears to create the Bookings and ToDo tables during the mix operation, so they don't exist on the SQL Server subsequently referenced.
What causes the initial creation of the Booking and ToDo tables? Where are they populated from?

This is my first experiment with ORMLite (I usually use LLBLGen Pro) so I might be missing something obvious.

**Comment by mythz** [comment]
running `x mix sqlserver` would apply [this gist](https://gist.github.com/gistlyn/04b77afa3aa33b653eca36a468df3150) to your project, i.e. overriding `Configure.Db.cs, Configure.Db.Migrations.cs,Migrations\Migration1000.cs`

Unfortunately that will override this templates ` Migrations\Migration1000.cs` back to a default table which you'll want to revert back by replacing it with the templates: https://github.com/NetCoreTemplates/nextjs/blob/main/api/MyApp/Migrations/Migration1000.cs

Since all the DB classes exist already in this template, you only needed to add the OrmLite.Sqlserver package with:

```
$ dotnet add package ServiceStack.OrmLite.SqlServer
```

Then replace the `ConfigureDb` class to use SqlServer:

```csharp
public class ConfigureDb : IHostingStartup
{
    public void Configure(IWebHostBuilder builder) => builder
        .ConfigureServices((context, services) => {
            services.AddSingleton<IDbConnectionFactory>(new OrmLiteConnectionFactory(
                context.Configuration.GetConnectionString("DefaultConnection")
                ?? "Server=localhost;Database=test;User Id=test;Password=test;MultipleActiveResultSets=True;",
                SqlServer2012Dialect.Provider));
        })
        .ConfigureAppHost(appHost => {
            // Enable built-in Database Admin UI at /admin-ui/database
            // appHost.Plugins.Add(new AdminDatabaseFeature());
        });
}
```

Once configured you should be able to run the DB Migrate task to create the DBs:

```
$ npm run migrate
```

See the docs to learn more about [OrmLite DB Migrations](https://docs.servicestack.net/ormlite/db-migrations).

**Comment by jsobell** [comment]
Ah, awesome, thanks.  I couldn't figure out where the database seeding had gone.
It might be worth adding either a flag or at least a comment in the doco explaining how to implement the template for different ORM engines, as this is a very powerful feature.
